SRC/GRAPHICS.CPP
SRC/PORT.CPP
SRC/PORT.H

Adjust palette brightness by the sine of brigthness instead of linearly. This makes the menu wobbling animation look like the original one.
Fix `tk_port_nanoclock()` implementation on Linux. Just work with nanoseconds from the beginning.
Adjust `VINTAGE_CLOCKS_PER_SEC`. The value of `22` seems to more or less match the experience of the original game on DosBox.

Palette and clock changes

---

SRC/GAME.CPP

Compilation on FreeBSD with Clang 6.0.0 fails when using `-Wall -Werror` compilation flags, because characters are being used as array indexes and Clang doesn't seem to allow that.

Do not use characters as array indexes

---

SRC/OPTIONS.CPP

Fixes runtime exceptions on Visual Studio and other possible erratic behavior.

Initialize "oclock" variables to fix runtime exceptions.

---

SRC/GAME.CPP

Index clearing comparison should be >= instead of >. Sometimes Visual Studio catches a stack corruption due to this.

Fix stack overflow with op table.

---

.travis.yml

Apparently Travis doesn't combine "common" packages (below) and explicitly set (`g++8` here). Hence repeating the SDL packages.
Adding GCC 8 because Net PR revealed that even if other compilers were happy in that case, GCC 8 wasn't and now we'll notice it automatically in the future.

Add GCC 8 to Travis CI script

---

SRC/I_FUNCS.H

If user had longer than 6 char name (game allows 9) and had no kills, text buffer overflowed (e.g. "No kills for veikkos" incl. termination is longer than the allocated 20 characters for `text` variable).
Increase buffer size and use buffer overflow protected functions.

Fix buffer overflow in statistics page.

---

.travis.yml

Net code and GCC 8 PR's were done in parallel so net library was missing from #44 .

Add missing libsdl2-net-dev to Travis CI's GCC 8 build.

---

README.md

Add x64-bit build instructions.
Add missing sdl2_net from cmake command.
Add instruction where to download SDL.

Readme improvements for Windows.

---

SRC/GAME.CPP
SRC/NET/NET.CPP
SRC/NET/NET.H

- Normalize and synchronize network refresh rate to other game logic (refresh rate).
- Network code speed was almost unlimited causing excessive package amounts.
- Implement packet envelope and proper buffers to stop packet loss.
- Now TK code will always receive just one packet at a time. Before it might have received several combined packets but it only processes the first one causing data loss.
- Decouple receiver indexes from socket indexes. Allows handling more than one packet per socket per frame.
- Fix use of uninitialized buffer value in realjoin. IPX_END was looked from one byte too far in the buffer and just sometimes happens to be corret value of 0.
- When closing the server, wait for a while before closing socket to allow clients to process DISCONNECT event. Not very pretty …

Buffer incoming network data to split game packets correctly

---

SRC/GAME.CPP

Fix enemies in split screen co-op mode.
Just to clarify that ENEMIES_ON_GAME is a Deathmatch-only setting (visible in UI). It's persistently stored to options file during game setup. It doesn't reflect the presence of enemies in non-deathmatch games.
Original condition was broken also for cases where persisting ENEMIES_ON_GAME was considered for non-deathmatch games.
Tested scenarios:
- Single player
- Split screen
- Deathmatch
- Co-op
- Network
- Server
- Deathmatch
- Co-op
- Client
Condition was shorted to implement as *if not true* due to less complex statements needed as opposed to *if true*. Other solutions welcome.
According to original TK 1.21 release notes this issue was eventually fixed but exists in the version this port is based on:
```
1.21- * One major bug fixed: The enemies …
```

Fix enemies in split screen co-op mode.

---

SRC/DEFINES.H
SRC/GAME.CPP
SRC/OPTIONS.CPP

Fix ESC key in episode selection menu. Without it there is no way to get back to main menu except going to game and back.

Fix ESC key in episode selection menu.

---

SRC/FUNCS.H

Pressing ESC without the fix froze the game.
Port tick was missing. Now exit prompt is opened.

Fix ESC not working in level info page.

---

SRC/PORT.CPP

The game window can be of any size. Draw the game screen as large as possible keeping the correct aspect ratio, centered in the direction in which the window is too big.
Fixes #53

Keep aspect ratio when the game window is resized

---

SRC/OPTIONS.CPP

Do not allow player to select cooperative play if game mode is Network. In case user has cooperative selected and they change from split screen to network game, automatically change mode to deathmatch.
Behavior is aligned with original TK 3.21.

Disallow network co-op as it is not implemented.

---

SRC/GAME.CPP

PR  #31 had a mistake which still let `check_places` function to read out-of-bounds memory. Fix was naturally supposed to return in case area is out of bounds.

Correction to check_places overflow fix.

---

SRC/DRAW.CPP

All other weapons than fists have bullet type > 0.
No need to anymore have (too late) explicit current weapon check for fists.
Fixes issue #11

Check bullet type before accessing player bullets.

---

SRC/PORT.CPP

When clearing screen with `SDL_RenderClear`, one should first set clearing color with `SDL_SetRenderDrawColor`.
Also clear the canvas during startup to avoid similar issues before first screen size or resolution change.

Remove potentially rendered garbage from borders

---

SRC/FADE.CPP
SRC/GAME.CPP
SRC/PORT.CPP

Issue #78 
Port framerate is limited to 4 times the target rate to mitigate any jitter.
Initialize SDL with required flags to remove unnecessary threads.
Move few event_tick calls so that they limit framerate in certain views.

Limit port framerate to avoid high CPU usage.

---

SRC/SOUND.CPP

Issues #82 #93 
Fix audio panning for proper stereo picture.
Scale music volume so that it matches effect volume.

Fix audio panning for proper stereo picture.

---

CMakeLists.txt
SRC/GAME.CPP
SRC/WRITE.CPP

Enable `WX` to treat warnings as errors.
Fix few warnings visible on some setups.

Enable warnings-as-errors on MSVC.

---

SRC/PORT.CPP

Issue #88 
More accurate FPS by using 1 ms timer callback and counting sub ticks.
Issue was due to mostly 1 ms too long SDL timer callback leading to too slow FPS in the ballpark of 3-4 %. This error is well within the expectations of SDL timer accuracy.
Fix balances sometimes slightly too short and sometimes slightly too long frametimes to near perfect _average_ of 25 ms frametime.
Compared to previous implementation we do compromise the frametime accuracy a bit. Is that a problem, probably not. Please comment if you think otherwise.
timer | avg [ms] | stdev [ms]
-- | -- | --
25 ms | 25,80 | 0,49
5 ms* | 25,00 | 2,34
1 ms* | 25,00 | 1,02
(*) with subticks.

More accurate FPS

---

SRC/GAME.CPP
SRC/KEYB.H

Issue #90 
F5 is the key used in TK321. Also gets rid of possible conflict with user selected keys as F5 is not possible player key.

Change Frames Per Second key from F to F5.

---

SRC/GAME.CPP

That feature has been removed since 1.2 beta. Tested with TK321 on DOSBox and it joins the game immeadiately without waiting for keypress.
Fixes issue #70

Remove waiting of keypress when joining network game as client.

---

SRC/OPTIONS.CPP

Issue #105 
Enemies are not supported over network.
Feature is now aligned with TK321.
Compared to TK321 with following scenario
- Player has enemies **enabled** in co-op game
- Player starts network game
- Enemies get automatically **disabled** and cannot be enabled
- Player returns to local co-op game
- Enemies are still **disabled** and player needs to manually enable them again
and the behavior is now same for the port.

Disallow enemies on network games.

---

README.md
SRC/CLASSES.CPP
SRC/CLASSES.H
SRC/CONTROLLER.CPP
SRC/CONTROLLER.H
SRC/CONTROLLERS.CPP
SRC/CONTROLLERS.H
SRC/DEFINES.H
SRC/GLOBVAR.CPP
SRC/GLOBVAR.H
SRC/INPUT.CPP
SRC/INPUT.H
SRC/KEYB.CPP
SRC/KEYB.H
SRC/MISCFUNC.CPP
SRC/MISCFUNC.H
SRC/PORT.CPP
SRC/TYPES.H
SRC/WRITE.CPP

Issue #102 (partial, to be splitted)
Emulate keyboard presses for at max two controllers. Controller keys need to be defined in options just like keyboard keys.
Limitations exist:
- Analog controllers not supported
- Includes triggers
- Controllers are able to do only "player" interactions, so cannot move in menus etc.
- Next iteration
- Primary and secondary controller assignment order is defined by  SDL
- ~Controller(s) need to be connected when game is started and controllers are not reconnected~
Both mappings tested separately with XBox One S controller. ~Two controllers not tested simultaneously due to lack of controllers.~ Good reason to invite a friend over with another controller.

Game controller support

---

SRC/MISCFUNC.CPP

Issue #108 
Fix incorrect player name order. Now shop and killing list show names in correct order.
Also change player color so that Player 1 is always red. Before the color changed to green if playing co-op. Why not to have same color for Player 1 in all modes.
If you don't like the more consistent player colors, please comment and I'll leave only the name bugfix. But for me it looks like that the original authors forgot to swap both name and color.

Fix incorrect player name order.

---

SRC/DRAW.CPP

Missing from #108  
Kill score colors are wrong way around in Deathmatch mode.

Fix hardcoded kill score colors.

---

README.md
SRC/CLASSES.CPP
SRC/DEFINES.H
SRC/DRAW.CPP
SRC/GAME.CPP
SRC/PORT_LEVEL.CPP
SRC/PORT_LEVEL.H
SRC/SOUND.CPP

* Replaces error-prone direct `level[y * w + x]` accesses with a helper function
* Adds `TK_MUTE_MUSIC` (it was interrupting my Spotify, grump grump)
* Adds `tk3 -e 1 -l 1` + `TK_SKIP_LEVEL_INFO` for immediate debug fun
Probably fixes #122.

Better level bounds checking (and developer QOL tools)

---

CMakeLists.txt

Build Visual C++ runtime statically into the executable.                                                                                                                                                                                                                                                                                                                                                    Avoid redistributing separate runtime DLLs or mandating full runtime installation.
https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2017
**Note**: Version 1 release was built with this flag.

Static Windows runtime

---

.travis.yml

Fix dependency installation failure on OSX builds.
```
Error: Your Homebrew is outdated. Please run `brew update`.
Error: Kernel.exit
```

Force brew update to avoid "outdated" error in CI

---

SRC/DEFINES.H
SRC/OPTIONS.CPP

(Partially) issue https://github.com/suomipelit/ultimatetapankaikki/issues/141
Force network clients to Deathmatch mode while joining. Fixes an issue where client had Cooperative mode selected while joining an online game and game misbehaves. Online games are always Deathmatch.
Bump version number to "SP3 SNAPSHOT" since this is a behavior change compared to SP2.

Force network clients to Deathmatch mode

---

SRC/GAME.CPP
SRC/PORT.CPP
SRC/PORT.H

- Yield control to the browser by manually calling `emscripten_sleep()` instead of letting SDL do it.
- Don't present the screen if nothing has changed. This gives better performance, as about 3 of 4 screen draws are skipped.

Manual Emscripten yield + optimize screen drawing

---

SRC/DEFINES.H
SRC/GAME.CPP
SRC/GLOBVAR.CPP
SRC/GLOBVAR.H
SRC/PORT.CPP
SRC/PORT.H

In original version network code was executed outside of game loop at unrestricted speed. Due to speed of modern computers, that's no longer a good idea since it leads to huge network traffic. Port synced network code speed to game logic.
However we have since implemented a speed limitter (160 Hz) so this PR moves the network refresh to be executed quicker than game logic to lessen latency.
Client logic was changed to send the keep-alive once per second.

Reduce network latency and traffic

---

SRC/GAME.CPP
SRC/NET/NET.CPP
SRC/NET/NET.H
SRC/NET/TRANSPORT/SDL/TRANSPORT.CPP

Close client socket on server side if keep-alive timeouts. Disconnects client correctly from server.
Partial fix to #141.
Unrelated: Fix socket deletion order. Close before delete.

Close client socket on keep-alive timeout

---

SRC/PORT_IMAGE.CPP

Crosshair and bomb sprites are 7x7 and hence 49 bytes are reserved for their data. Those images have pitch of 8 - but only 7 bytes should be copied to avoid writing extra byte after every row. At last row it means that buffer overflow of 1 byte happens.

Fix small sprite loading buffer overflow

---

SRC/NET/TRANSPORT/WEBRTC/TRANSPORT.JS

RTCDataChannel's default binary type seems to be arraybuffer on Chrome, but Firefox has "blob". This broke message decoding.

Fix WebRTC networking on Firefox

---

CMakeLists.txt
SRC/MISCFUNC.CPP
SRC/OPTIONS.CPP
SRC/PORT.CPP
SRC/PORT.H

Issue #145 
Use [Indexed Database](https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api-idbfs) for storing options persistently.
Database is mounted at `/persistent` for read and write access. It needs to be done in port init and synchronized so that option reading works correctly.
Edit: [Now live.](https://suomipelit.github.io/ultimatetapankaikki-web/)

Persistent options for web port

---

SRC/CLASSES.CPP

Local deathmatch game with enemies crashes on either player's death.
Message should be inside `P`'s null check. `P` points to the the killer, and it null if the killer is a CPU enemy player. There should be no kill message in such case.

Local deathmatch game with enemies crashes on death

---

README.md
SRC/MISCFUNC.CPP
SRC/MISCFUNC.H
SRC/OPTIONS.CPP
SRC/WRITE.CPP

Resolves #169 
Resolves #142 
Prompt player name if starting online game (as a host or as a client) if player 1 still has the default name.
Fix issue where player is left with empty name if pressing ESC in name prompt.

Prompt player name for network games and keep name with ESC

---

README.md
SRC/WRITE.CPP

Resolves #177 
Use new text input method in readline to support copy-paste in name and server address/ID input fields.

Use new input method for text fields

---

README.md
SRC/DEFINES.H
SRC/GAME.CPP
SRC/GLOBVAR.CPP
SRC/GLOBVAR.H
SRC/MISCFUNC.CPP
SRC/MISCFUNC.H
SRC/OPTIONS.CPP

Fixes #187 
Allow setting a game name for online games. Option is skipped for Split Screen games as is Password option.

Online game name feature

---

SRC/GAME.CPP

Pressing enter in non-network games lead to the game taking no input anymore.
Fixes #192

Only start text chat in network games
